function logHandoverEvent(logFile, currentTime, hoEventData)
    fid = fopen(logFile, 'a');
    if fid == -1, return; end

    fprintf(fid, 'TIMESTAMP: %d, UE_ID: %d, CELL_SOURCE_ID: %d, CELL_TARGET_ID: %d, RSRP_SOURCE: %.2f, RSRP_TARGET: %.2f, RSRQ_SOURCE: %.2f, RSRQ_TARGET: %.2f, SINR_SOURCE: %.2f, SINR_TARGET: %.2f, TIME_TO_TRIGGER: %.2f, A3_OFFSET: %.2f, HOF: %d\n', currentTime, hoEventData.ue_id, ...
        hoEventData.cell_source, hoEventData.cell_target, ...
        hoEventData.rsrp_source, hoEventData.rsrp_target, ...
        hoEventData.rsrq_source, hoEventData.rsrq_target, ...
        hoEventData.sinr_source, hoEventData.sinr_target, ...
        hoEventData.ttt, hoEventData.a3_offset, ...
        hoEventData.ho_success);

    fclose(fid);
end