function ueStates = captureUEState(ues, currentTime)
    ueStateArray = struct('id', {}, 'x', {}, 'y', {}, 'servingCell', {}, ...
                         'rsrp', {}, 'rsrq', {}, 'sinr', {}, 'mobilityPattern', {});
    
    for i = 1:length(ues)
        ueStateArray(i) = struct(...
            'id', ues(i).id, ...
            'x', ues(i).x, ...
            'y', ues(i).y, ...
            'servingCell', ues(i).servingCell, ...
            'rsrp', ues(i).rsrp, ...
            'rsrq', ues(i).rsrq, ...
            'sinr', ues(i).sinr, ...
            'mobilityPattern', ues(i).mobilityPattern ...
        );
    end
    
    ueStates = struct('time', currentTime, 'ueStates', ueStateArray);
end